### ISSUE TITLE
Import does not work because dependencies are not listed correctly.

### ISSUE THREAD

**Issue by phx-mkoninckx** [ansys/pymodelcenter#192]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Importing the package does not work, because the dependency on `ansys-engineeringworkflow-api` is listed only as a test dependency.

### 📝 Steps to reproduce

1. Install the ModelCenter API package: `pip install ansys-modelcenter-workflow`
2. Then, from within the Python interpreter, attempt to import it: `import ansys.modelcenter.workflow.grpc_modelcenter as grpcmc`

The import fails, with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mkoninck\repro_venv\lib\site-packages\ansys\modelcenter\workflow\grpc_modelcenter\__init__.py", line 28, in <module>
    from .abstract_workflow_element import UnsupportedWorkflowElement
  File "C:\Users\mkoninck\repro_venv\lib\site-packages\ansys\modelcenter\workflow\grpc_modelcenter\abstract_workflow_element.py", line 27, in <module>
    import ansys.engineeringworkflow.api as aew_api
ModuleNotFoundError: No module named 'ansys.engineeringworkflow'
```

Inspection of the `pyproject.toml` for this package shows that `ansys-engineeringworkflow-api` is listed only as a test dependency (which allows the CI tests to pass even though an end user will inevitably encounter this). **Manual installation of `ansys-engineeringworkflow-api` allows this package to function, and can be used as a workaround at the moment.**

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
(repro_venv) C:\Users\mkoninck\repro_venv>python -m pip freeze
ansys-api-modelcenter==0.3.1
ansys-api-platform-instancemanagement==1.0.0
ansys-modelcenter-workflow==0.1.0
ansys-platform-instancemanagement==1.1.2
anyio==4.3.0
exceptiongroup==1.2.0
grpcio==1.62.1
idna==3.6
importlib_metadata==7.1.0
numpy==1.26.4
overrides==7.7.0
protobuf==4.25.3
pyansys-tools-variableinterop==0.1.1
sniffio==1.3.1
typing_extensions==4.10.0
zipp==3.18.1
```

**Comment by phx-mkoninckx** [comment]
[Release 0.1.1](https://pypi.org/project/ansys-modelcenter-workflow/0.1.1/) provides a fix for this issue as a hotfix.
